/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelP13(props) {
  const { nodes, materials } = useGLTF('/p13.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.1, 0.04, 0.18]}>
        <mesh geometry={nodes.mesh_25_4.geometry} material={materials['Material.060']} />
        <mesh geometry={nodes.mesh_25_1.geometry} material={materials['Material.064']} />
        <mesh geometry={nodes.mesh_25_3.geometry} material={materials['Material.065']} />
        <mesh geometry={nodes.mesh_25_5.geometry} material={materials['Material.061']} />
        <mesh geometry={nodes.mesh_25_2.geometry} material={materials['Material.063']} />
        <mesh geometry={nodes.mesh_25_0.geometry} material={materials['Material.062']} />
      </group>
    </group>
  )
}

useGLTF.preload('/p13.glb')
