/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelP17(props) {
  const { nodes, materials } = useGLTF('/p17.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.1, 0.04, 0.18]}>
        <mesh geometry={nodes.mesh_31_4.geometry} material={materials['Material.054']} />
        <mesh geometry={nodes.mesh_31_0.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.mesh_31_5.geometry} material={materials['Material.055']} />
        <mesh geometry={nodes.mesh_31_2.geometry} material={materials['Material.057']} />
        <mesh geometry={nodes.mesh_31_3.geometry} material={materials['Material.059']} position={[0, 0, -0.02]} />
        <mesh geometry={nodes.mesh_31_1.geometry} material={materials['Material.058']} />
      </group>
    </group>
  )
}

useGLTF.preload('/p17.glb')
