/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelP18(props) {
  const { nodes, materials } = useGLTF('/p18.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.1, 0.04, 0.18]}>
        <mesh geometry={nodes.mesh_21_1.geometry} material={materials['Material.070']} />
        <mesh geometry={nodes.mesh_21_2.geometry} material={materials['Material.069']} />
        <mesh geometry={nodes.mesh_21_4.geometry} material={materials['Material.066']} />
        <mesh geometry={nodes.mesh_21_0.geometry} material={materials['Material.068']} />
        <mesh geometry={nodes.mesh_21_3.geometry} material={materials['Material.071']} />
        <mesh geometry={nodes.mesh_21_5.geometry} material={materials['Material.067']} />
      </group>
    </group>
  )
}

useGLTF.preload('/p18.glb')
